/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as D1RouteImport } from './routes/d1'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as KvRouteImport } from './routes/kv'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QueuesRouteImport } from './routes/queues'
import { Route as R2RouteImport } from './routes/r2'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as D1NewRouteImport } from './routes/d1_.new'
import { Route as KvNewRouteImport } from './routes/kv_.new'
import { Route as ProjectsNameRouteImport } from './routes/projects_.$name'
import { Route as QueuesNewRouteImport } from './routes/queues_.new'
import { Route as R2NewRouteImport } from './routes/r2_.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsTokensRouteImport } from './routes/settings.tokens'
import { Route as SettingsUsageRouteImport } from './routes/settings.usage'
import { Route as ProjectsNameIndexRouteImport } from './routes/projects_.$name.index'
import { Route as ProjectsNameBindingsRouteImport } from './routes/projects_.$name.bindings'
import { Route as ProjectsNameDeploymentsRouteImport } from './routes/projects_.$name.deployments'
import { Route as ProjectsNameLogsRouteImport } from './routes/projects_.$name.logs'
import { Route as ProjectsNameMetricsRouteImport } from './routes/projects_.$name.metrics'
import { Route as ProjectsNameSettingsRouteImport } from './routes/projects_.$name.settings'
import { Route as ProjectsNameTriggersRouteImport } from './routes/projects_.$name.triggers'
import { Route as ProjectsNameDeploymentsIdRouteImport } from './routes/projects_.$name.deployments_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const D1Route = D1RouteImport.update({
  id: '/d1',
  path: '/d1',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const KvRoute = KvRouteImport.update({
  id: '/kv',
  path: '/kv',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesRoute = QueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => rootRouteImport,
} as any)
const R2Route = R2RouteImport.update({
  id: '/r2',
  path: '/r2',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const D1NewRoute = D1NewRouteImport.update({
  id: '/d1_/new',
  path: '/d1/new',
  getParentRoute: () => rootRouteImport,
} as any)
const KvNewRoute = KvNewRouteImport.update({
  id: '/kv_/new',
  path: '/kv/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNameRoute = ProjectsNameRouteImport.update({
  id: '/projects_/$name',
  path: '/projects/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesNewRoute = QueuesNewRouteImport.update({
  id: '/queues_/new',
  path: '/queues/new',
  getParentRoute: () => rootRouteImport,
} as any)
const R2NewRoute = R2NewRouteImport.update({
  id: '/r2_/new',
  path: '/r2/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsNameIndexRoute = ProjectsNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameBindingsRoute = ProjectsNameBindingsRouteImport.update({
  id: '/bindings',
  path: '/bindings',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameDeploymentsRoute = ProjectsNameDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameLogsRoute = ProjectsNameLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameMetricsRoute = ProjectsNameMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameSettingsRoute = ProjectsNameSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameTriggersRoute = ProjectsNameTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameDeploymentsIdRoute =
  ProjectsNameDeploymentsIdRouteImport.update({
    id: '/deployments_/$id',
    path: '/deployments/$id',
    getParentRoute: () => ProjectsNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/d1': typeof D1Route
  '/deployments': typeof DeploymentsRoute
  '/kv': typeof KvRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/queues': typeof QueuesRoute
  '/r2': typeof R2Route
  '/settings': typeof SettingsRouteWithChildren
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/users': typeof AdminUsersRoute
  '/d1/new': typeof D1NewRoute
  '/kv/new': typeof KvNewRoute
  '/projects/$name': typeof ProjectsNameRouteWithChildren
  '/queues/new': typeof QueuesNewRoute
  '/r2/new': typeof R2NewRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$name/bindings': typeof ProjectsNameBindingsRoute
  '/projects/$name/deployments': typeof ProjectsNameDeploymentsRoute
  '/projects/$name/logs': typeof ProjectsNameLogsRoute
  '/projects/$name/metrics': typeof ProjectsNameMetricsRoute
  '/projects/$name/settings': typeof ProjectsNameSettingsRoute
  '/projects/$name/triggers': typeof ProjectsNameTriggersRoute
  '/projects/$name/': typeof ProjectsNameIndexRoute
  '/projects/$name/deployments/$id': typeof ProjectsNameDeploymentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/d1': typeof D1Route
  '/deployments': typeof DeploymentsRoute
  '/kv': typeof KvRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/queues': typeof QueuesRoute
  '/r2': typeof R2Route
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/users': typeof AdminUsersRoute
  '/d1/new': typeof D1NewRoute
  '/kv/new': typeof KvNewRoute
  '/queues/new': typeof QueuesNewRoute
  '/r2/new': typeof R2NewRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/admin': typeof AdminIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/$name/bindings': typeof ProjectsNameBindingsRoute
  '/projects/$name/deployments': typeof ProjectsNameDeploymentsRoute
  '/projects/$name/logs': typeof ProjectsNameLogsRoute
  '/projects/$name/metrics': typeof ProjectsNameMetricsRoute
  '/projects/$name/settings': typeof ProjectsNameSettingsRoute
  '/projects/$name/triggers': typeof ProjectsNameTriggersRoute
  '/projects/$name': typeof ProjectsNameIndexRoute
  '/projects/$name/deployments/$id': typeof ProjectsNameDeploymentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/d1': typeof D1Route
  '/deployments': typeof DeploymentsRoute
  '/kv': typeof KvRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/queues': typeof QueuesRoute
  '/r2': typeof R2Route
  '/settings': typeof SettingsRouteWithChildren
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/users': typeof AdminUsersRoute
  '/d1_/new': typeof D1NewRoute
  '/kv_/new': typeof KvNewRoute
  '/projects_/$name': typeof ProjectsNameRouteWithChildren
  '/queues_/new': typeof QueuesNewRoute
  '/r2_/new': typeof R2NewRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects_/$name/bindings': typeof ProjectsNameBindingsRoute
  '/projects_/$name/deployments': typeof ProjectsNameDeploymentsRoute
  '/projects_/$name/logs': typeof ProjectsNameLogsRoute
  '/projects_/$name/metrics': typeof ProjectsNameMetricsRoute
  '/projects_/$name/settings': typeof ProjectsNameSettingsRoute
  '/projects_/$name/triggers': typeof ProjectsNameTriggersRoute
  '/projects_/$name/': typeof ProjectsNameIndexRoute
  '/projects_/$name/deployments_/$id': typeof ProjectsNameDeploymentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/d1'
    | '/deployments'
    | '/kv'
    | '/login'
    | '/profile'
    | '/projects'
    | '/queues'
    | '/r2'
    | '/settings'
    | '/admin/backups'
    | '/admin/users'
    | '/d1/new'
    | '/kv/new'
    | '/projects/$name'
    | '/queues/new'
    | '/r2/new'
    | '/settings/tokens'
    | '/settings/usage'
    | '/admin/'
    | '/settings/'
    | '/projects/$name/bindings'
    | '/projects/$name/deployments'
    | '/projects/$name/logs'
    | '/projects/$name/metrics'
    | '/projects/$name/settings'
    | '/projects/$name/triggers'
    | '/projects/$name/'
    | '/projects/$name/deployments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/d1'
    | '/deployments'
    | '/kv'
    | '/login'
    | '/profile'
    | '/projects'
    | '/queues'
    | '/r2'
    | '/admin/backups'
    | '/admin/users'
    | '/d1/new'
    | '/kv/new'
    | '/queues/new'
    | '/r2/new'
    | '/settings/tokens'
    | '/settings/usage'
    | '/admin'
    | '/settings'
    | '/projects/$name/bindings'
    | '/projects/$name/deployments'
    | '/projects/$name/logs'
    | '/projects/$name/metrics'
    | '/projects/$name/settings'
    | '/projects/$name/triggers'
    | '/projects/$name'
    | '/projects/$name/deployments/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/d1'
    | '/deployments'
    | '/kv'
    | '/login'
    | '/profile'
    | '/projects'
    | '/queues'
    | '/r2'
    | '/settings'
    | '/admin/backups'
    | '/admin/users'
    | '/d1_/new'
    | '/kv_/new'
    | '/projects_/$name'
    | '/queues_/new'
    | '/r2_/new'
    | '/settings/tokens'
    | '/settings/usage'
    | '/admin/'
    | '/settings/'
    | '/projects_/$name/bindings'
    | '/projects_/$name/deployments'
    | '/projects_/$name/logs'
    | '/projects_/$name/metrics'
    | '/projects_/$name/settings'
    | '/projects_/$name/triggers'
    | '/projects_/$name/'
    | '/projects_/$name/deployments_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  D1Route: typeof D1Route
  DeploymentsRoute: typeof DeploymentsRoute
  KvRoute: typeof KvRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  QueuesRoute: typeof QueuesRoute
  R2Route: typeof R2Route
  SettingsRoute: typeof SettingsRouteWithChildren
  D1NewRoute: typeof D1NewRoute
  KvNewRoute: typeof KvNewRoute
  ProjectsNameRoute: typeof ProjectsNameRouteWithChildren
  QueuesNewRoute: typeof QueuesNewRoute
  R2NewRoute: typeof R2NewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d1': {
      id: '/d1'
      path: '/d1'
      fullPath: '/d1'
      preLoaderRoute: typeof D1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kv': {
      id: '/kv'
      path: '/kv'
      fullPath: '/kv'
      preLoaderRoute: typeof KvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues': {
      id: '/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof QueuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r2': {
      id: '/r2'
      path: '/r2'
      fullPath: '/r2'
      preLoaderRoute: typeof R2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/d1_/new': {
      id: '/d1_/new'
      path: '/d1/new'
      fullPath: '/d1/new'
      preLoaderRoute: typeof D1NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kv_/new': {
      id: '/kv_/new'
      path: '/kv/new'
      fullPath: '/kv/new'
      preLoaderRoute: typeof KvNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$name': {
      id: '/projects_/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof ProjectsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues_/new': {
      id: '/queues_/new'
      path: '/queues/new'
      fullPath: '/queues/new'
      preLoaderRoute: typeof QueuesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r2_/new': {
      id: '/r2_/new'
      path: '/r2/new'
      fullPath: '/r2/new'
      preLoaderRoute: typeof R2NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects_/$name/': {
      id: '/projects_/$name/'
      path: '/'
      fullPath: '/projects/$name/'
      preLoaderRoute: typeof ProjectsNameIndexRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/bindings': {
      id: '/projects_/$name/bindings'
      path: '/bindings'
      fullPath: '/projects/$name/bindings'
      preLoaderRoute: typeof ProjectsNameBindingsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/deployments': {
      id: '/projects_/$name/deployments'
      path: '/deployments'
      fullPath: '/projects/$name/deployments'
      preLoaderRoute: typeof ProjectsNameDeploymentsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/logs': {
      id: '/projects_/$name/logs'
      path: '/logs'
      fullPath: '/projects/$name/logs'
      preLoaderRoute: typeof ProjectsNameLogsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/metrics': {
      id: '/projects_/$name/metrics'
      path: '/metrics'
      fullPath: '/projects/$name/metrics'
      preLoaderRoute: typeof ProjectsNameMetricsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/settings': {
      id: '/projects_/$name/settings'
      path: '/settings'
      fullPath: '/projects/$name/settings'
      preLoaderRoute: typeof ProjectsNameSettingsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/triggers': {
      id: '/projects_/$name/triggers'
      path: '/triggers'
      fullPath: '/projects/$name/triggers'
      preLoaderRoute: typeof ProjectsNameTriggersRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/deployments_/$id': {
      id: '/projects_/$name/deployments_/$id'
      path: '/deployments/$id'
      fullPath: '/projects/$name/deployments/$id'
      preLoaderRoute: typeof ProjectsNameDeploymentsIdRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBackupsRoute: AdminBackupsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SettingsRouteChildren {
  SettingsTokensRoute: typeof SettingsTokensRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsTokensRoute: SettingsTokensRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ProjectsNameRouteChildren {
  ProjectsNameBindingsRoute: typeof ProjectsNameBindingsRoute
  ProjectsNameDeploymentsRoute: typeof ProjectsNameDeploymentsRoute
  ProjectsNameLogsRoute: typeof ProjectsNameLogsRoute
  ProjectsNameMetricsRoute: typeof ProjectsNameMetricsRoute
  ProjectsNameSettingsRoute: typeof ProjectsNameSettingsRoute
  ProjectsNameTriggersRoute: typeof ProjectsNameTriggersRoute
  ProjectsNameIndexRoute: typeof ProjectsNameIndexRoute
  ProjectsNameDeploymentsIdRoute: typeof ProjectsNameDeploymentsIdRoute
}

const ProjectsNameRouteChildren: ProjectsNameRouteChildren = {
  ProjectsNameBindingsRoute: ProjectsNameBindingsRoute,
  ProjectsNameDeploymentsRoute: ProjectsNameDeploymentsRoute,
  ProjectsNameLogsRoute: ProjectsNameLogsRoute,
  ProjectsNameMetricsRoute: ProjectsNameMetricsRoute,
  ProjectsNameSettingsRoute: ProjectsNameSettingsRoute,
  ProjectsNameTriggersRoute: ProjectsNameTriggersRoute,
  ProjectsNameIndexRoute: ProjectsNameIndexRoute,
  ProjectsNameDeploymentsIdRoute: ProjectsNameDeploymentsIdRoute,
}

const ProjectsNameRouteWithChildren = ProjectsNameRoute._addFileChildren(
  ProjectsNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  D1Route: D1Route,
  DeploymentsRoute: DeploymentsRoute,
  KvRoute: KvRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  QueuesRoute: QueuesRoute,
  R2Route: R2Route,
  SettingsRoute: SettingsRouteWithChildren,
  D1NewRoute: D1NewRoute,
  KvNewRoute: KvNewRoute,
  ProjectsNameRoute: ProjectsNameRouteWithChildren,
  QueuesNewRoute: QueuesNewRoute,
  R2NewRoute: R2NewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
