/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBackupsRouteImport } from './routes/admin.backups'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ProjectsNameRouteImport } from './routes/projects_.$name'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsTokensRouteImport } from './routes/settings.tokens'
import { Route as SettingsUsageRouteImport } from './routes/settings.usage'
import { Route as StorageKindRouteImport } from './routes/storage_.$kind'
import { Route as ProjectsNameIndexRouteImport } from './routes/projects_.$name.index'
import { Route as ProjectsNameBindingsRouteImport } from './routes/projects_.$name.bindings'
import { Route as ProjectsNameDeploymentsRouteImport } from './routes/projects_.$name.deployments'
import { Route as ProjectsNameLogsRouteImport } from './routes/projects_.$name.logs'
import { Route as ProjectsNameMetricsRouteImport } from './routes/projects_.$name.metrics'
import { Route as ProjectsNameSettingsRouteImport } from './routes/projects_.$name.settings'
import { Route as ProjectsNameTriggersRouteImport } from './routes/projects_.$name.triggers'
import { Route as ProjectsNameDeploymentsIdRouteImport } from './routes/projects_.$name.deployments_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsNameRoute = ProjectsNameRouteImport.update({
  id: '/projects_/$name',
  path: '/projects/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTokensRoute = SettingsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const StorageKindRoute = StorageKindRouteImport.update({
  id: '/storage_/$kind',
  path: '/storage/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNameIndexRoute = ProjectsNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameBindingsRoute = ProjectsNameBindingsRouteImport.update({
  id: '/bindings',
  path: '/bindings',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameDeploymentsRoute = ProjectsNameDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameLogsRoute = ProjectsNameLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameMetricsRoute = ProjectsNameMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameSettingsRoute = ProjectsNameSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameTriggersRoute = ProjectsNameTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => ProjectsNameRoute,
} as any)
const ProjectsNameDeploymentsIdRoute =
  ProjectsNameDeploymentsIdRouteImport.update({
    id: '/deployments_/$id',
    path: '/deployments/$id',
    getParentRoute: () => ProjectsNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/deployments': typeof DeploymentsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/storage': typeof StorageRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects/$name': typeof ProjectsNameRouteWithChildren
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/storage/$kind': typeof StorageKindRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$name/bindings': typeof ProjectsNameBindingsRoute
  '/projects/$name/deployments': typeof ProjectsNameDeploymentsRoute
  '/projects/$name/logs': typeof ProjectsNameLogsRoute
  '/projects/$name/metrics': typeof ProjectsNameMetricsRoute
  '/projects/$name/settings': typeof ProjectsNameSettingsRoute
  '/projects/$name/triggers': typeof ProjectsNameTriggersRoute
  '/projects/$name/': typeof ProjectsNameIndexRoute
  '/projects/$name/deployments/$id': typeof ProjectsNameDeploymentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deployments': typeof DeploymentsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/storage': typeof StorageRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/users': typeof AdminUsersRoute
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/storage/$kind': typeof StorageKindRoute
  '/admin': typeof AdminIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/$name/bindings': typeof ProjectsNameBindingsRoute
  '/projects/$name/deployments': typeof ProjectsNameDeploymentsRoute
  '/projects/$name/logs': typeof ProjectsNameLogsRoute
  '/projects/$name/metrics': typeof ProjectsNameMetricsRoute
  '/projects/$name/settings': typeof ProjectsNameSettingsRoute
  '/projects/$name/triggers': typeof ProjectsNameTriggersRoute
  '/projects/$name': typeof ProjectsNameIndexRoute
  '/projects/$name/deployments/$id': typeof ProjectsNameDeploymentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/deployments': typeof DeploymentsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/storage': typeof StorageRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/users': typeof AdminUsersRoute
  '/projects_/$name': typeof ProjectsNameRouteWithChildren
  '/settings/tokens': typeof SettingsTokensRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/storage_/$kind': typeof StorageKindRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects_/$name/bindings': typeof ProjectsNameBindingsRoute
  '/projects_/$name/deployments': typeof ProjectsNameDeploymentsRoute
  '/projects_/$name/logs': typeof ProjectsNameLogsRoute
  '/projects_/$name/metrics': typeof ProjectsNameMetricsRoute
  '/projects_/$name/settings': typeof ProjectsNameSettingsRoute
  '/projects_/$name/triggers': typeof ProjectsNameTriggersRoute
  '/projects_/$name/': typeof ProjectsNameIndexRoute
  '/projects_/$name/deployments_/$id': typeof ProjectsNameDeploymentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/deployments'
    | '/login'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/storage'
    | '/admin/backups'
    | '/admin/users'
    | '/projects/$name'
    | '/settings/tokens'
    | '/settings/usage'
    | '/storage/$kind'
    | '/admin/'
    | '/settings/'
    | '/projects/$name/bindings'
    | '/projects/$name/deployments'
    | '/projects/$name/logs'
    | '/projects/$name/metrics'
    | '/projects/$name/settings'
    | '/projects/$name/triggers'
    | '/projects/$name/'
    | '/projects/$name/deployments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deployments'
    | '/login'
    | '/profile'
    | '/projects'
    | '/storage'
    | '/admin/backups'
    | '/admin/users'
    | '/settings/tokens'
    | '/settings/usage'
    | '/storage/$kind'
    | '/admin'
    | '/settings'
    | '/projects/$name/bindings'
    | '/projects/$name/deployments'
    | '/projects/$name/logs'
    | '/projects/$name/metrics'
    | '/projects/$name/settings'
    | '/projects/$name/triggers'
    | '/projects/$name'
    | '/projects/$name/deployments/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/deployments'
    | '/login'
    | '/profile'
    | '/projects'
    | '/settings'
    | '/storage'
    | '/admin/backups'
    | '/admin/users'
    | '/projects_/$name'
    | '/settings/tokens'
    | '/settings/usage'
    | '/storage_/$kind'
    | '/admin/'
    | '/settings/'
    | '/projects_/$name/bindings'
    | '/projects_/$name/deployments'
    | '/projects_/$name/logs'
    | '/projects_/$name/metrics'
    | '/projects_/$name/settings'
    | '/projects_/$name/triggers'
    | '/projects_/$name/'
    | '/projects_/$name/deployments_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DeploymentsRoute: typeof DeploymentsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StorageRoute: typeof StorageRoute
  ProjectsNameRoute: typeof ProjectsNameRouteWithChildren
  StorageKindRoute: typeof StorageKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects_/$name': {
      id: '/projects_/$name'
      path: '/projects/$name'
      fullPath: '/projects/$name'
      preLoaderRoute: typeof ProjectsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tokens': {
      id: '/settings/tokens'
      path: '/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof SettingsTokensRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/storage_/$kind': {
      id: '/storage_/$kind'
      path: '/storage/$kind'
      fullPath: '/storage/$kind'
      preLoaderRoute: typeof StorageKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$name/': {
      id: '/projects_/$name/'
      path: '/'
      fullPath: '/projects/$name/'
      preLoaderRoute: typeof ProjectsNameIndexRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/bindings': {
      id: '/projects_/$name/bindings'
      path: '/bindings'
      fullPath: '/projects/$name/bindings'
      preLoaderRoute: typeof ProjectsNameBindingsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/deployments': {
      id: '/projects_/$name/deployments'
      path: '/deployments'
      fullPath: '/projects/$name/deployments'
      preLoaderRoute: typeof ProjectsNameDeploymentsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/logs': {
      id: '/projects_/$name/logs'
      path: '/logs'
      fullPath: '/projects/$name/logs'
      preLoaderRoute: typeof ProjectsNameLogsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/metrics': {
      id: '/projects_/$name/metrics'
      path: '/metrics'
      fullPath: '/projects/$name/metrics'
      preLoaderRoute: typeof ProjectsNameMetricsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/settings': {
      id: '/projects_/$name/settings'
      path: '/settings'
      fullPath: '/projects/$name/settings'
      preLoaderRoute: typeof ProjectsNameSettingsRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/triggers': {
      id: '/projects_/$name/triggers'
      path: '/triggers'
      fullPath: '/projects/$name/triggers'
      preLoaderRoute: typeof ProjectsNameTriggersRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
    '/projects_/$name/deployments_/$id': {
      id: '/projects_/$name/deployments_/$id'
      path: '/deployments/$id'
      fullPath: '/projects/$name/deployments/$id'
      preLoaderRoute: typeof ProjectsNameDeploymentsIdRouteImport
      parentRoute: typeof ProjectsNameRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBackupsRoute: AdminBackupsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SettingsRouteChildren {
  SettingsTokensRoute: typeof SettingsTokensRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsTokensRoute: SettingsTokensRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ProjectsNameRouteChildren {
  ProjectsNameBindingsRoute: typeof ProjectsNameBindingsRoute
  ProjectsNameDeploymentsRoute: typeof ProjectsNameDeploymentsRoute
  ProjectsNameLogsRoute: typeof ProjectsNameLogsRoute
  ProjectsNameMetricsRoute: typeof ProjectsNameMetricsRoute
  ProjectsNameSettingsRoute: typeof ProjectsNameSettingsRoute
  ProjectsNameTriggersRoute: typeof ProjectsNameTriggersRoute
  ProjectsNameIndexRoute: typeof ProjectsNameIndexRoute
  ProjectsNameDeploymentsIdRoute: typeof ProjectsNameDeploymentsIdRoute
}

const ProjectsNameRouteChildren: ProjectsNameRouteChildren = {
  ProjectsNameBindingsRoute: ProjectsNameBindingsRoute,
  ProjectsNameDeploymentsRoute: ProjectsNameDeploymentsRoute,
  ProjectsNameLogsRoute: ProjectsNameLogsRoute,
  ProjectsNameMetricsRoute: ProjectsNameMetricsRoute,
  ProjectsNameSettingsRoute: ProjectsNameSettingsRoute,
  ProjectsNameTriggersRoute: ProjectsNameTriggersRoute,
  ProjectsNameIndexRoute: ProjectsNameIndexRoute,
  ProjectsNameDeploymentsIdRoute: ProjectsNameDeploymentsIdRoute,
}

const ProjectsNameRouteWithChildren = ProjectsNameRoute._addFileChildren(
  ProjectsNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DeploymentsRoute: DeploymentsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StorageRoute: StorageRoute,
  ProjectsNameRoute: ProjectsNameRouteWithChildren,
  StorageKindRoute: StorageKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
