import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { EmptyChart, Metric, Shell } from "../components";

export const Route = createFileRoute("/dashboard")({ component: Dashboard, head: () => ({ meta: [{ title: "Dashboard · Porffer" }] }) });

function Dashboard() {
  const [isOperator, setIsOperator] = useState(false);
  const [cliCode, setCliCode] = useState<string>();
  const [signedIn, setSignedIn] = useState(false);
  const [hasNamespace, setHasNamespace] = useState(false);
  const [username, setUsername] = useState("");
  useEffect(() => { setCliCode(new URLSearchParams(location.search).get("cli_code") || undefined); void fetch("/v1/me", { credentials: "include" }).then(async (response) => { setSignedIn(response.ok); return response.ok ? response.json() : null; }).then((data) => { setIsOperator(data?.isOperator === true); setHasNamespace(Boolean(data?.profile)); }).catch(() => setIsOperator(false)); }, []);
  const signIn = async () => { const response = await fetch("/api/auth/sign-in/social", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider: "github", callbackURL: location.href }) }); const data = await response.json() as { url?: string }; if (data.url) location.assign(data.url); };
  const approve = async () => { if (!cliCode) return; await fetch(`/v1/cli/authorizations/${encodeURIComponent(cliCode)}/approve`, { method: "POST", credentials: "include" }); history.replaceState({}, "", "/dashboard"); setCliCode(undefined); };
  const reserve = async () => { const response = await fetch("/v1/me/namespace", { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ username }) }); if (response.ok) setHasNamespace(true); };
  return <Shell isOperator={isOperator}>{cliCode && <section className="panel"><h2>Connect Porffer CLI</h2><p>{signedIn && hasNamespace ? "Approve this browser login to save a local CLI credential." : "Finish account setup at the Porffer home page before approving this CLI login."}</p><button className="button primary" type="button" disabled={!signedIn || !hasNamespace} onClick={approve}>Approve CLI login</button></section>}<section className="page-heading"><div><p className="eyebrow">Developer workspace</p><h1>Ship with confidence.</h1><p className="lede">Deploy locally compiled Porffer artifacts, then watch the routes that are live.</p></div><button className="button primary" type="button">Deploy a Porffer</button></section><section className="metrics" aria-label="Deployment statistics"><Metric label="Active projects" value="—" detail="Loading your workspace" tone="purple" /><Metric label="Deployments" value="—" detail="Across all versions" /><Metric label="Requests" value="—" detail="No metrics loaded yet" /><Metric label="Success rate" value="—" detail="Available after traffic" /></section><div className="content-grid"><EmptyChart label="Request volume" note="Your traffic, over time" /><section className="panel" id="deployments"><div className="panel-heading"><div><p className="mono-label">Deployments</p><h2>Recent activity</h2></div><a href="#projects">View all</a></div><div className="empty-state"><span className="empty-icon">↗</span><h3>No deployments to show</h3><p>Run <code>porffer deploy</code> to create the first immutable version.</p></div></section></div><section className="panel table-panel" id="projects"><div className="panel-heading"><div><p className="mono-label">Projects</p><h2>Your routes</h2></div><button className="button ghost" type="button">Create project</button></div><div className="empty-table"><span>Project details load from the Control API after sign-in.</span></div></section></Shell>;
}
