import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { basename, resolve } from "node:path";
import { connect } from "node:net";
import { compileHandler } from "./compile";
import { fixtures } from "./fixtures";
import { invokeHandler, loadHandler } from "./refserve";
import { porfforVersion } from "./porffor";
import type { CompatReport, FileResult, RequestFixture, ResponseSnapshot } from "./types";

const root = resolve(import.meta.dir, "..");
const capabilitiesDir = resolve(root, "tests/porffor/capabilities");
const reuseBinaries = process.env.PORFFOR_REUSE_BINARIES === "1";
// SAFETY: report.json is generated by this tool and has the CompatReport contract.
const previousReport: CompatReport | null = reuseBinaries
  ? JSON.parse(await readFile(resolve(root, "report.json"), "utf8"))
  : null;

let nextPort = 47_000;

function requestFrom(fixture: RequestFixture): Request {
  const init: RequestInit = { method: fixture.method, headers: fixture.headers };
  if (fixture.method !== "GET" && fixture.method !== "HEAD") init.body = fixture.body;
  return new Request(fixture.url, init);
}

async function normalize(response: Response): Promise<ResponseSnapshot> {
  return { status: response.status, body: await response.text(), "content-type": response.headers.get("content-type") };
}

async function listens(port: number): Promise<boolean> {
  return new Promise((done) => {
    const socket = connect({ host: "127.0.0.1", port }, () => { socket.destroy(); done(true); });
    socket.on("error", () => done(false));
  });
}

/** Run a compiled native-fetch sprout once and probe it with every fixture. */
async function probe(binary: string): Promise<ResponseSnapshot[]> {
  const port = nextPort++;
  const child = Bun.spawn([binary], { stdout: "ignore", stderr: "pipe", env: { ...process.env, PORT: String(port) } });
  try {
    const deadline = Date.now() + 5_000;
    while (!(await listens(port))) {
      if (Date.now() > deadline) throw new Error("server did not start");
      if (await Promise.race([child.exited.then(() => true), Bun.sleep(25).then(() => false)])) {
        throw new Error((await new Response(child.stderr).text()).trim() || "server exited before listening");
      }
    }
    const out: ResponseSnapshot[] = [];
    for (const fixture of fixtures) {
      const target = new URL(fixture.url);
      target.protocol = "http:"; target.hostname = "127.0.0.1"; target.port = String(port);
      const init: RequestInit = { method: fixture.method, headers: fixture.headers };
      if (fixture.method !== "GET" && fixture.method !== "HEAD") init.body = fixture.body;
      out.push(await normalize(await fetch(target, init)));
    }
    return out;
  } finally {
    child.kill(9);
    await child.exited;
  }
}

function same(left: ResponseSnapshot, right: ResponseSnapshot): boolean {
  return left.status === right.status && left.body === right.body && left["content-type"] === right["content-type"];
}

function concise(error: string | Error | null): string {
  const ansi = new RegExp(`${String.fromCharCode(27)}\\[[0-9;]*m`, "g");
  return String(error).replace(ansi, "").replace(/\s+/g, " ").trim().slice(0, 500);
}

async function testFile(file: string): Promise<FileResult> {
  const sourcePath = resolve(capabilitiesDir, file);
  const previous = previousReport?.files.find((item) => item.file === file);
  const reusedPath = resolve(root, ".phase0/bin", basename(file, ".js"));
  const compiled = reuseBinaries && previous?.compiles
    ? { ok: true, binaryPath: reusedPath, sizeBytes: (await stat(reusedPath)).size, compileMs: previous.compileMs, error: null }
    : await compileHandler(sourcePath);
  const base = { file, compiles: compiled.ok, sizeBytes: compiled.sizeBytes, compileMs: Math.round(compiled.compileMs), runMs: null };
  if (!compiled.ok || !compiled.binaryPath) return { ...base, matches: false, error: concise(compiled.error) };

  const started = performance.now();
  try {
    const handler = await loadHandler(sourcePath);
    const native = await probe(compiled.binaryPath);
    for (let index = 0; index < fixtures.length; index++) {
      const reference = await normalize(await invokeHandler(handler, requestFrom(fixtures[index])));
      if (!same(reference, native[index])) {
        return { ...base, matches: false, runMs: Math.round(performance.now() - started), error: `request ${index + 1} mismatch: expected ${JSON.stringify(reference)}, got ${JSON.stringify(native[index])}` };
      }
    }
    return { ...base, matches: true, runMs: Math.round(performance.now() - started), error: null };
  } catch (error) {
    return { ...base, matches: false, runMs: Math.round(performance.now() - started), error: concise(error instanceof Error ? error : String(error)) };
  }
}

const files = (await readdir(capabilitiesDir)).filter((file) => file.endsWith(".js")).sort();
const results: FileResult[] = [];
for (const [index, file] of files.entries()) {
  console.log(`[${index + 1}/${files.length}] ${file}`);
  results.push(await testFile(file));
}

const report: CompatReport = {
  generatedAt: new Date().toISOString(),
  porfforVersion: porfforVersion(),
  requestsPerFile: fixtures.length,
  files: results,
};
await writeFile(resolve(root, "report.json"), `${JSON.stringify(report, null, 2)}\n`);
console.log(`wrote report.json (${results.filter((item) => item.matches).length}/${results.length} match)`);
